import { invoke } from '@tauri-apps/api/core'
import type {
  AppSettings, BootstrapData, CardProgress, CourseClass, DocumentDetail, DocumentFolder, DocumentSummary, LectureDetail, LectureSummary, RevisionHistoryEntry,
  Flashcard, FlashcardSetDetail, FlashcardSetSummary, SearchResult, SecurityStatus, Semester, StudyInsights, StudySessionSummary, StudyWebDetail, StudyWebRelationship, StudyWebSummary, TestAttemptSummary,
} from './types'

const mutatingCommands = new Set(['create_semester', 'update_semester', 'delete_semester', 'create_class', 'update_class', 'delete_class', 'create_document', 'save_document', 'name_document_revision', 'restore_document_revision', 'create_lecture', 'save_lecture', 'name_lecture_revision', 'restore_lecture_revision', 'delete_lecture', 'set_document_syllabus', 'set_document_deleted', 'duplicate_document', 'rename_documents', 'rename_document_folder', 'group_documents', 'remove_document_from_folder', 'move_document', 'create_flashcard_set', 'save_flashcard_set', 'set_flashcard_set_deleted', 'duplicate_flashcard_set', 'save_flashcard', 'delete_flashcard', 'create_empty_study_web', 'import_study_web_json', 'generate_study_web', 'set_study_web_deleted', 'save_study_web_node_position', 'toggle_study_web_relationship', 'update_study_web_group_membership', 'create_study_web_group', 'record_card_response', 'start_study_session', 'complete_study_session', 'save_test_attempt', 'save_match_time', 'update_settings', 'delete_local_ai_models', 'empty_trash', 'update_library_security', 'restore_library'])
const call = async <T>(command: string, arguments_?: Record<string, unknown>) => {
  const result = await invoke<T>(command, arguments_)
  if (mutatingCommands.has(command)) await invoke('sync_encrypted_library')
  return result
}

export const api = {
  isInstallerLaunch: () => invoke<boolean>('is_installer_launch'),
  installerVersionInfo: () => invoke<{ currentVersion: string; targetVersion: string }>('installer_version_info'),
  runInstallerWorker: () => invoke<void>('run_installer_worker'),
  launchInstalledSofloAndClose: () => invoke<void>('launch_installed_soflo_and_close'),
  bootstrap: () => call<BootstrapData>('bootstrap'),
  listSemesters: (includeArchived = false) => call<Semester[]>('list_semesters', { includeArchived }),
  createSemester: (input: { name: string; term: string; year: number }) => call<Semester>('create_semester', { input }),
  updateSemester: (input: { id: string; name: string; term: string; year: number; archived: boolean }) => call<Semester>('update_semester', { input }),
  deleteSemester: (id: string) => call<void>('delete_semester', { id }),
  listClasses: (includeArchived = false) => call<CourseClass[]>('list_classes', { includeArchived }),
  createClass: (input: { semesterId: string; name: string; courseCode: string; professor?: string; location?: string; schedule?: string; icon?: string; accentColor?: string }) => call<CourseClass>('create_class', { input }),
  updateClass: (input: { id: string; semesterId: string; name: string; courseCode: string; professor?: string | null; location?: string | null; schedule?: string | null; icon: string; accentColor: string; archived: boolean }) => call<CourseClass>('update_class', { input }),
  deleteClass: (id: string) => call<void>('delete_class', { id }),
  listDocuments: (classId: string, includeDeleted = false) => call<DocumentSummary[]>('list_documents', { classId, includeDeleted }),
  listDocumentRevisions: (id: string) => call<RevisionHistoryEntry[]>('list_document_revisions', { id }),
  nameDocumentRevision: (revisionId: string, name: string) => call<void>('name_document_revision', { revisionId, name }),
  restoreDocumentRevision: (id: string, revisionId: string) => call<DocumentDetail>('restore_document_revision', { id, revisionId }),
  listRecentDocuments: () => call<DocumentSummary[]>('list_recent_documents'),
  getDocument: (id: string) => call<DocumentDetail>('get_document', { id }),
  getSyllabus: (classId: string) => call<DocumentDetail | null>('get_syllabus', { classId }),
  createDocument: (input: { classId: string; title: string }) => call<DocumentDetail>('create_document', { input }),
  saveDocument: (input: Pick<DocumentDetail, 'id' | 'title' | 'content' | 'contentPlain' | 'isFavorite'>) => call<DocumentDetail>('save_document', { input }),
  listLectures: (classId: string) => call<LectureSummary[]>('list_lectures', { classId }),
  listLectureRevisions: (id: string) => call<RevisionHistoryEntry[]>('list_lecture_revisions', { id }),
  nameLectureRevision: (revisionId: string, name: string) => call<void>('name_lecture_revision', { revisionId, name }),
  restoreLectureRevision: (id: string, revisionId: string) => call<LectureDetail>('restore_lecture_revision', { id, revisionId }),
  getLecture: (id: string) => call<LectureDetail>('get_lecture', { id }),
  createLecture: (input: { classId: string; courseCode: string; courseName: string; lectureDate: string; scheduledStart: string | null; scheduledEnd: string | null; professorSnapshot: string | null; title: string }) => call<LectureDetail>('create_lecture', { input }),
  saveLecture: (input: Pick<LectureDetail, 'id' | 'title' | 'content' | 'contentPlain'>) => call<LectureDetail>('save_lecture', { input }),
  deleteLecture: (id: string) => call<void>('delete_lecture', { id }),
  setDocumentSyllabus: (id: string) => call<DocumentDetail>('set_document_syllabus', { id }),
  setDocumentDeleted: (id: string, deleted: boolean) => call<void>('set_document_deleted', { id, deleted }),
  duplicateDocument: (id: string, title?: string) => call<DocumentDetail>('duplicate_document', { id, title }),
  renameDocuments: (documents: { id: string; title: string }[]) => call<void>('rename_documents', { input: { documents } }),
  setDocumentPdfLink: (id: string, path: string | null) => call<void>('set_document_pdf_link', { id, path }),
  listDocumentFolders: (classId: string) => call<DocumentFolder[]>('list_document_folders', { classId }),
  renameDocumentFolder: (id: string, title: string) => call<void>('rename_document_folder', { id, title }),
  groupDocuments: (id: string, targetId: string) => call<void>('group_documents', { id, targetId }),
  removeDocumentFromFolder: (id: string) => call<void>('remove_document_from_folder', { id }),
  moveDocument: (id: string, classId: string) => call<void>('move_document', { id, classId }),
  listSets: (classId: string, includeDeleted = false) => call<FlashcardSetSummary[]>('list_flashcard_sets', { classId, includeDeleted }),
  createSet: (input: { classId: string; title: string; description?: string }) => call<FlashcardSetDetail>('create_flashcard_set', { input }),
  getSet: (id: string) => call<FlashcardSetDetail>('get_flashcard_set', { id }),
  saveSet: (input: { id: string; title: string; description?: string | null }) => call<FlashcardSetDetail>('save_flashcard_set', { input }),
  setSetDeleted: (id: string, deleted: boolean) => call<void>('set_flashcard_set_deleted', { id, deleted }),
  duplicateSet: (id: string, title: string) => call<FlashcardSetDetail>('duplicate_flashcard_set', { id, title }),
  saveCard: (input: { id?: string; setId: string; front: string; back: string; notes?: string | null; imagePath?: string | null; position: number; isStarred: boolean }) => call<Flashcard>('save_flashcard', { input }),
  deleteCard: (id: string) => call<void>('delete_flashcard', { id }),
  listAllCards: (classId: string) => call<Flashcard[]>('list_all_cards', { classId }),
  listStudyWebs: (classId: string) => call<StudyWebSummary[]>('list_study_webs', { classId }),
  listTrashedStudyWebs: (classId: string) => call<StudyWebSummary[]>('list_trashed_study_webs', { classId }),
  getStudyWeb: (id: string) => call<StudyWebDetail>('get_study_web', { id }),
  setStudyWebDeleted: (id: string, deleted: boolean) => call<void>('set_study_web_deleted', { id, deleted }),
  createEmptyStudyWeb: (classId: string, name = 'Study Web') => call<StudyWebDetail>('create_empty_study_web', { classId, name }),
  exportStudyWebJson: (id: string) => call<string>('export_study_web_json', { id }),
  importStudyWebJson: (classId: string, source: string) => call<StudyWebDetail>('import_study_web_json', { classId, source }),
  generateStudyWeb: (input: { setIds: string[]; modelPath: string; studyWebId?: string }) => call<StudyWebDetail>('generate_study_web', { setIds: input.setIds, modelPath: input.modelPath, studyWebId: input.studyWebId ?? null }),
  saveStudyWebNodePosition: (input: { studyWebId: string; cardId: string; x: number; y: number; pinned?: boolean }) => call<void>('save_study_web_node_position', { input }),
  toggleStudyWebRelationship: (input: { studyWebId: string; sourceCardId: string; targetCardId: string }) => call<StudyWebRelationship | null>('toggle_study_web_relationship', { input }),
  updateStudyWebGroupMembership: (input: { studyWebId: string; groupId: string; cardId: string; included: boolean }) => call<StudyWebDetail>('update_study_web_group_membership', { input }),
  createStudyWebGroup: (input: { studyWebId: string; cardId: string; label: string }) => call<StudyWebDetail>('create_study_web_group', { input }),
  recordCardResponse: (cardId: string, isCorrect: boolean, details?: { sessionId?: string; mode?: string; questionType?: string; answer?: string }) => call<CardProgress>('record_card_response', { input: { cardId, isCorrect, ...details } }),
  startStudySession: (input: { setId: string; mode: string }) => call<StudySessionSummary>('start_study_session', { input }),
  completeStudySession: (id: string) => call<void>('complete_study_session', { input: { id } }),
  getStudyInsights: (classId: string) => call<StudyInsights>('get_study_insights', { classId }),
  saveTestAttempt: (input: { setId: string; score: number; correctCount: number; questionCount: number; answersJson: string }) => call<TestAttemptSummary>('save_test_attempt', { input }),
  getMatchBestTime: (setId: string) => call<number | null>('get_match_best_time', { setId }),
  saveMatchTime: (setId: string, seconds: number) => call<number>('save_match_time', { setId, seconds }),
  exportFlashcardSetText: (setId: string) => call<string>('export_flashcard_set_text', { setId }),
  readTextFile: (path: string) => call<string>('read_text_file', { path }),
  updateSettings: (settings: AppSettings) => call<AppSettings>('update_settings', { input: { settings } }),
  emptyTrash: () => call<void>('empty_trash'),
  getSecurityStatus: () => call<SecurityStatus>('get_security_status'),
  unlockLibrary: (input: { pin?: string; password?: string }) => call<SecurityStatus>('unlock_library', { input }),
  updateLibrarySecurity: (input: { currentPin?: string; currentPassword?: string; newPin?: string; newPassword?: string; removePin: boolean; removePassword: boolean }) => call<SecurityStatus>('update_library_security', { input }),
  syncEncryptedLibrary: () => call<void>('sync_encrypted_library'),
  search: (query: string) => call<SearchResult[]>('search_library', { query }),
  backupLibrary: (destination: string) => call<void>('backup_library', { destination }),
  restoreLibrary: (source: string) => call<void>('restore_library', { source }),
  defaultSofloExportPath: () => call<string>('default_soflo_export_path'),
  exportSofloData: (destination: string) => call<void>('export_soflo_data', { destination }),
  importSofloDataAndRestart: (source: string) => call<void>('import_soflo_data_and_restart', { source }),
  wipeSofloDataAndRestart: () => call<void>('wipe_soflo_data_and_restart'),
  importPdfText: (path: string) => call<string>('import_pdf_text', { path }),
  importSyllabusPdfText: (path: string) => call<string>('import_syllabus_pdf_text', { path }),
  importWordText: (path: string) => call<string>('import_word_text', { path }),
  refineDocumentText: (modelPath: string, text: string, documentKind: 'paper' | 'syllabus') => call<string>('refine_document_text', { modelPath, text, documentKind }),
  generateFlashcardsText: (modelPath: string, materials: string, guidance: string) => call<string>('generate_flashcards_text', { modelPath, materials, guidance }),
  generateTeachItBackQuestion: (modelPath: string, front: string, back: string, shownSide: 'front' | 'back', difficulty: 'easy' | 'hard') => call<string>('generate_teach_it_back_question', { modelPath, front, back, shownSide, difficulty }),
  gradeTeachItBackAnswer: (modelPath: string, front: string, back: string, question: string, target: string, answer: string) => call<string>('grade_teach_it_back_answer', { modelPath, front, back, question, target, answer }),
  reviewGrammarText: (modelPath: string, text: string, quick: boolean, paperContext: string) => call<string>('review_grammar_text', { modelPath, text, quick, paperContext }),
  researchAndGradeText: (modelPath: string, text: string, paperContext: string) => call<string>('research_and_grade_text', { modelPath, text, paperContext }),
  defineWord: (modelPath: string, word: string, paperContext: string) => call<string>('define_word', { modelPath, word, paperContext }),
  aiThesaurus: (modelPath: string, word: string, paperContext: string) => call<string>('ai_thesaurus', { modelPath, word, paperContext }),
  wordAiModelReady: () => call<boolean>('word_ai_model_ready'),
  stopAiServer: () => call<void>('stop_ai_server'),
  downloadDefaultAiModel: () => call<string>('download_default_ai_model'),
  deleteLocalAiModels: () => call<void>('delete_local_ai_models'),
}
