import { type FormEvent, useState } from 'react'
import { FormModal } from '../../components/Modal'
import type { Semester } from '../../lib/types'

type Meeting = { day: string; start: string; end: string }
const weekdays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']

export function CreateSemesterDialog({ onClose, onCreate }: { onClose: () => void; onCreate: (input: { name: string; term: string; year: number }) => Promise<void> }) {
  const currentYear = new Date().getFullYear(); const [term, setTerm] = useState('Fall'); const [year, setYear] = useState(currentYear); const [name, setName] = useState(`Fall ${currentYear}`); const [saving, setSaving] = useState(false)
  const updateTerm = (nextTerm: string) => { setTerm(nextTerm); if (!name.trim() || name === `${term} ${year}`) setName(`${nextTerm} ${year}`) }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!name.trim()) return; setSaving(true); try { await onCreate({ name: name.trim(), term, year }) } finally { setSaving(false) } }
  return <FormModal title="New semester" onClose={onClose} onSubmit={submit} submitLabel="Create semester" saving={saving}><label>Semester name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Fall 2026" required /></label><div className="form-grid"><label>Term<select value={term} onChange={(event) => updateTerm(event.target.value)}><option>Spring</option><option>Summer</option><option>Fall</option><option>Winter</option></select></label><label>Year<input type="number" min="2000" max="2100" value={year} onChange={(event) => setYear(Number(event.target.value))} required /></label></div></FormModal>
}

export function CreateClassDialog({ semesters, initialSemesterId, onClose, onCreate }: { semesters: Semester[]; initialSemesterId?: string; onClose: () => void; onCreate: (input: { semesterId: string; name: string; courseCode: string; professor?: string; location?: string; schedule?: string; accentColor?: string }) => Promise<void> }) {
  const [semesterId, setSemesterId] = useState(initialSemesterId ?? semesters[0]?.id ?? ''); const [name, setName] = useState(''); const [courseCode, setCourseCode] = useState(''); const [professor, setProfessor] = useState(''); const [location, setLocation] = useState(''); const [meetings, setMeetings] = useState<Meeting[]>([]); const [scheduleOpen, setScheduleOpen] = useState(false); const [accentColor, setAccentColor] = useState('#8B7CF6'); const [saving, setSaving] = useState(false)
  const schedule = meetings.length ? meetings.map((meeting) => `${meeting.day} ${formatTime(meeting.start)}-${formatTime(meeting.end)}`).join('; ') : undefined
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!name.trim() || !semesterId) return; setSaving(true); try { await onCreate({ semesterId, name: name.trim(), courseCode: courseCode.trim(), professor: professor.trim() || undefined, location: location.trim() || undefined, schedule, accentColor }) } finally { setSaving(false) } }
  return <>{scheduleOpen && <ClassScheduleDialog initial={meetings} onClose={() => setScheduleOpen(false)} onConfirm={(next) => { setMeetings(next); setScheduleOpen(false) }} />}<FormModal title="New class" onClose={onClose} onSubmit={submit} submitLabel="Create class" saving={saving}><label>Semester<select value={semesterId} onChange={(event) => setSemesterId(event.target.value)}>{semesters.map((semester) => <option key={semester.id} value={semester.id}>{semester.name}</option>)}</select></label><div className="form-grid"><label>Class name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Intro to Programming" required /></label><label>Course code<input value={courseCode} onChange={(event) => setCourseCode(event.target.value)} placeholder="CSCI 130" /></label></div><div className="form-grid"><label>Professor <span className="optional">optional</span><input value={professor} onChange={(event) => setProfessor(event.target.value)} placeholder="Dr. Nguyen" /></label><label>Room / location <span className="optional">optional</span><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Science 204" /></label></div><div className="schedule-summary"><div><strong>Class schedule</strong><small>{schedule ?? 'No meeting times set yet.'}</small></div><button type="button" className="button button-quiet button-small" onClick={() => setScheduleOpen(true)}>Set class schedule</button></div><div className="accent-picker"><span>Accent</span>{['#8B7CF6', '#5AA6E6', '#52A682', '#D49352', '#D56D8A', '#9A80C9', '#E05A7C', '#3AB5A0', '#E2B34F', '#5887E8', '#C56BE1'].map((color) => <button type="button" key={color} onClick={() => setAccentColor(color)} className={accentColor === color ? 'selected' : ''} style={{ background: color }} aria-label={`Use ${color} accent`} />)}</div></FormModal></>
}

function ClassScheduleDialog({ initial, onClose, onConfirm }: { initial: Meeting[]; onClose: () => void; onConfirm: (meetings: Meeting[]) => void }) {
  const [meetings, setMeetings] = useState(initial)
  const selected = (day: string) => meetings.find((meeting) => meeting.day === day)
  const toggle = (day: string) => setMeetings((current) => selected(day) ? current.filter((meeting) => meeting.day !== day) : [...current, { day, start: '09:00', end: '10:00' }])
  const update = (day: string, field: 'start' | 'end', value: string) => setMeetings((current) => current.map((meeting) => meeting.day === day ? { ...meeting, [field]: value } : meeting))
  return <div className="security-dialog-backdrop" role="presentation"><section className="security-dialog class-schedule-dialog" role="dialog" aria-modal="true" aria-label="Set class schedule"><header><div><p className="eyebrow">CLASS CALENDAR</p><h2>Set class schedule</h2></div><button className="icon-button" onClick={onClose}>×</button></header><div className="security-dialog-content"><p className="schedule-dialog-copy">Choose the weekdays first, then give each meeting its own start and end time.</p><div className="meeting-days">{weekdays.map((day) => <button type="button" key={day} className={selected(day) ? 'selected' : ''} onClick={() => toggle(day)}>{day}</button>)}</div>{meetings.sort((a, b) => weekdays.indexOf(a.day) - weekdays.indexOf(b.day)).map((meeting) => <div className="meeting-time-row" key={meeting.day}><strong>{meeting.day}</strong><label>Start<input type="time" value={meeting.start} onChange={(event) => update(meeting.day, 'start', event.target.value)} /></label><label>End<input type="time" value={meeting.end} onChange={(event) => update(meeting.day, 'end', event.target.value)} /></label></div>)}<div className="security-dialog-actions"><button className="button button-quiet" onClick={onClose}>Cancel</button><button className="button button-primary" onClick={() => onConfirm(meetings)}>Confirm schedule</button></div></div></section></div>
}

function formatTime(value: string) { const [hourValue, minute] = value.split(':').map(Number); const period = hourValue >= 12 ? 'PM' : 'AM'; return `${hourValue % 12 || 12}:${String(minute).padStart(2, '0')} ${period}` }
