import { Archive, BookOpen, Copy, FilePlus2, FileText, FileUp, GraduationCap, LayoutList, MoreHorizontal, NotebookPen, Plus, RotateCcw, Sparkles, Star, Trash2, X } from 'lucide-react'
import { useEffect, useLayoutEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import type { AppView, CourseClass, DocumentDetail, DocumentFolder, DocumentSummary, Flashcard, FlashcardSetSummary, LectureSummary, StudyInsights } from '../../lib/types'
import { api } from '../../lib/api'
import { formatDate } from '../../lib/format'
import { DocumentsView } from '../editor/DocumentsView'
import { LecturesView } from '../lectures/LecturesView'

interface ClassViewProps { course: CourseClass; tab: Extract<AppView, { kind: 'class' }>['tab']; documentCount: number; documents: DocumentSummary[]; folders: DocumentFolder[]; lectures: LectureSummary[]; syllabus: DocumentDetail | null; aiEnabled: boolean; trashedDocuments: DocumentSummary[]; sets: FlashcardSetSummary[]; trashedSets: FlashcardSetSummary[]; allCards: Flashcard[]; onTab: (tab: Extract<AppView, { kind: 'class' }>['tab']) => void; onNewDocument: () => void; onNewLecture: () => void; onImportPdf: () => void; onImportSyllabus: () => void; onNewSet: () => void; onImportSet: () => void; onNewAiSet: () => void; onOpenDocument: (document: DocumentSummary) => void; onOpenLecture: (lecture: LectureSummary) => void; onDeleteLecture: (lecture: LectureSummary) => void; onTrashDocument: (document: DocumentSummary) => void; onDuplicateDocument: (document: DocumentSummary, title: string) => void; onBulkRename: (papers: { id: string; title: string }[]) => void; onGroupDocuments: (id: string, targetId: string) => void; onUngroupDocument: (id: string) => void; onRenameDocumentFolder: (id: string, title: string) => void; onOpenSet: (id: string) => void; onStudyWeak: (setId: string, cardIds: string[]) => void; onDuplicateSet: (set: FlashcardSetSummary, title: string) => void; onTrashSet: (set: FlashcardSetSummary) => void; onRestoreDocument: (id: string) => void; onRestoreSet: (id: string) => void; onArchive: () => void }
const tabs: { key: ClassViewProps['tab']; label: string; icon: typeof LayoutList }[] = [{ key: 'overview', label: 'Overview', icon: LayoutList }, { key: 'notes', label: 'Papers', icon: FilePlus2 }, { key: 'lectures', label: 'Lectures', icon: NotebookPen }, { key: 'syllabus', label: 'Syllabus', icon: FileText }, { key: 'flashcards', label: 'Flashcards', icon: BookOpen }, { key: 'study', label: 'Study', icon: Sparkles }, { key: 'trash', label: 'Trash', icon: Trash2 }]

export function ClassView(p: ClassViewProps) { return <main className="class-view"><header className="class-header content-view"><div className="class-title-line"><span className="large-class-icon" style={{ background: p.course.accentColor }}><GraduationCap size={21} /></span><div><p className="eyebrow">{p.course.courseCode || 'CLASS'}</p><h1>{p.course.name}</h1></div><button className="icon-button class-more" aria-label="Archive class" onClick={p.onArchive}><Archive size={17} /></button></div><div className="class-meta">{p.course.professor && <span>{p.course.professor}</span>}{p.course.location && <span>{p.course.location}</span>}{p.course.schedule && <span>{p.course.schedule}</span>}</div><nav className="class-tabs" aria-label={`${p.course.name} navigation`}>{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.key} className={p.tab === tab.key ? 'active' : ''} onClick={() => p.onTab(tab.key)}><Icon size={15} />{tab.label}</button> })}</nav></header><div className="content-view class-content">{p.tab === 'overview' && <Overview {...p} />}{p.tab === 'notes' && <DocumentsView documents={p.documents} folders={p.folders} aiEnabled={p.aiEnabled} onOpen={p.onOpenDocument} onCreate={p.onNewDocument} onImportPdf={p.onImportPdf} onTrash={p.onTrashDocument} onDuplicate={p.onDuplicateDocument} onBulkRename={p.onBulkRename} onGroup={p.onGroupDocuments} onUngroup={p.onUngroupDocument} onRenameFolder={p.onRenameDocumentFolder} />}{p.tab === 'lectures' && <LecturesView lectures={p.lectures} onCreate={p.onNewLecture} onOpen={p.onOpenLecture} onDelete={p.onDeleteLecture} />}{p.tab === 'syllabus' && <SyllabusView syllabus={p.syllabus} aiEnabled={p.aiEnabled} onImport={p.onImportSyllabus} />}{p.tab === 'flashcards' && <SetsLanding sets={p.sets} allCards={p.allCards} aiEnabled={p.aiEnabled} onNewSet={p.onNewSet} onImportSet={p.onImportSet} onNewAiSet={p.onNewAiSet} onOpenSet={p.onOpenSet} onDuplicateSet={p.onDuplicateSet} onTrashSet={p.onTrashSet} />}{p.tab === 'study' && <StudyLanding courseId={p.course.id} sets={p.sets} onOpenSet={p.onOpenSet} onStudyWeak={p.onStudyWeak} />}{p.tab === 'trash' && <TrashLanding documents={p.trashedDocuments} sets={p.trashedSets} onRestoreDocument={p.onRestoreDocument} onRestoreSet={p.onRestoreSet} />}</div></main> }

function SyllabusView({ syllabus, aiEnabled, onImport }: { syllabus: DocumentDetail | null; aiEnabled: boolean; onImport: () => void }) { if (!syllabus) return <section className="section-blank syllabus-empty"><FileText size={28} /><h2>Add your class syllabus.</h2><p>Import a PDF or Word document and SoFlo will turn its text into a read-only paper for this class.</p><button className={`button button-primary${aiEnabled ? ' ai-action' : ''}`} onClick={onImport}><FileUp size={16} /> Import syllabus</button></section>; return <section className="syllabus-view"><div className="section-heading"><div><h2>Syllabus</h2><p>Class syllabus.</p></div><button className={`button button-quiet button-small${aiEnabled ? ' ai-action' : ''}`} onClick={onImport}><FileUp size={15} /> Replace syllabus</button></div><SyllabusContent syllabus={syllabus} /></section> }
type SyllabusNode = { type?: string; text?: string; marks?: { type?: string }[]; attrs?: { level?: number }; content?: SyllabusNode[] }
const nodeText = (node: SyllabusNode): string => node.text ?? node.content?.map(nodeText).join('') ?? ''
const syllabusText = (node: SyllabusNode): ReactNode => { if (node.type === 'hardBreak') return <br />; if (node.text === undefined) return node.content?.map((child, index) => <span key={index}>{syllabusText(child)}</span>); const text = node.marks?.some((mark) => mark.type === 'bold') ? <strong>{node.text}</strong> : markdownBold(node.text); return node.marks?.some((mark) => mark.type === 'italic') ? <em>{text}</em> : text }
const markdownBold = (text: string) => text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean).map((part, index) => part.startsWith('**') && part.endsWith('**') ? <strong key={index}>{part.slice(2, -2)}</strong> : <span key={index}>{part}</span>)
function SyllabusContent({ syllabus }: { syllabus: DocumentDetail }) {
  const nodes = useMemo(() => {
    try {
      const parsed = JSON.parse(syllabus.content) as SyllabusNode
      return parsed.content?.length ? parsed.content : [{ type: 'paragraph', content: [] }]
    } catch {
      return [{ type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: syllabus.title || 'Syllabus' }] }, { type: 'paragraph', content: [{ type: 'text', text: syllabus.contentPlain || 'This syllabus is empty.' }] }]
    }
  }, [syllabus.content, syllabus.contentPlain, syllabus.title])
  const measureRef = useRef<HTMLDivElement>(null)
  const [pageIndexes, setPageIndexes] = useState<number[][]>(() => [nodes.map((_, index) => index)])
  useLayoutEffect(() => {
    const measure = measureRef.current
    if (!measure) return
    let frame = 0
    const paginate = () => {
      const capacity = measure.clientHeight
      const elements = Array.from(measure.children) as HTMLElement[]
      if (!capacity || elements.length !== nodes.length) return
      const next: number[][] = [[]]
      let used = 0
      elements.forEach((element, index) => {
        const style = window.getComputedStyle(element)
        const height = element.getBoundingClientRect().height + Number.parseFloat(style.marginBottom || '0')
        if (next[next.length - 1].length && used + height > capacity) { next.push([]); used = 0 }
        next[next.length - 1].push(index)
        used += height
      })
      setPageIndexes((current) => JSON.stringify(current) === JSON.stringify(next) ? current : next)
    }
    const schedule = () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(paginate) }
    schedule()
    const observer = new ResizeObserver(schedule)
    observer.observe(measure)
    window.addEventListener('resize', schedule)
    return () => { cancelAnimationFrame(frame); observer.disconnect(); window.removeEventListener('resize', schedule) }
  }, [nodes])
  const pages = pageIndexes.flat().length === nodes.length ? pageIndexes : [nodes.map((_, index) => index)]
  return <><div className="syllabus-measure" ref={measureRef} aria-hidden="true">{nodes.map((node, index) => <div className="syllabus-node" key={index}>{renderNode(node, index)}</div>)}</div><div className="syllabus-page-stack">{pages.map((page, pageIndex) => <article className="document-page syllabus-paper" key={pageIndex}><div className="syllabus-paper-content">{page.map((nodeIndex) => <div className="syllabus-node" key={nodeIndex}>{renderNode(nodes[nodeIndex], nodeIndex)}</div>)}</div><span className="syllabus-page-number" aria-label={`Page ${pageIndex + 1}`}>{pageIndex + 1}</span></article>)}</div></>
}
function renderNode(node: SyllabusNode, key: number): ReactNode { const text = syllabusText(node); if (node.type === 'heading') { const Tag = `h${Math.min(3, Math.max(1, node.attrs?.level ?? 2))}` as 'h1' | 'h2' | 'h3'; return <Tag key={key}>{text}</Tag> }; if (node.type === 'bulletList' || node.type === 'orderedList') { const Tag = node.type === 'bulletList' ? 'ul' : 'ol'; return <Tag key={key}>{node.content?.map((item, index) => <li key={index}>{syllabusText(item)}</li>)}</Tag> }; if (node.type === 'table') return <table key={key}><tbody>{node.content?.map((row, rowIndex) => <tr key={rowIndex}>{row.content?.map((cell, cellIndex) => cell.type === 'tableHeader' ? <th key={cellIndex}>{syllabusText(cell)}</th> : <td key={cellIndex}>{syllabusText(cell)}</td>)}</tr>)}</tbody></table>; if (node.type === 'horizontalRule') return <hr key={key} />; return <p key={key}>{text}</p> }

function Overview(p: ClassViewProps) { const [hidden, setHidden] = useState(() => localStorage.getItem('soflo:hide-overview-banner') === 'true'); const hide = () => { localStorage.setItem('soflo:hide-overview-banner', 'true'); setHidden(true) }; return <>{!hidden && <section className="overview-hero" style={{ '--course-accent': p.course.accentColor } as React.CSSProperties}><div><p className="eyebrow">YOUR WORKSPACE</p><h2>Ready when you are.</h2><p>Write a paper, review a set, or pick up where you left off.</p></div><div className="overview-actions"><button className="button button-light" onClick={p.onNewDocument}><FilePlus2 size={16} /> New paper</button><button className="button button-soft" onClick={p.onNewSet}><BookOpen size={16} /> New set</button></div><button className="overview-hide" onClick={hide}>Hide</button></section>}<section className="overview-metrics"><div><span>{p.documentCount}</span><small>{p.documentCount === 1 ? 'paper' : 'papers'}</small></div><div><span>{p.sets.length}</span><small>{p.sets.length === 1 ? 'flashcard set' : 'flashcard sets'}</small></div><div><span>{p.sets.reduce((total, set) => total + set.cardCount, 0)}</span><small>cards to review</small></div></section><section className="class-section"><div className="section-heading"><div><h2>Flashcard sets</h2><p>Keep your review material close to your papers.</p></div>{p.sets.length > 0 && <button className="text-button" onClick={p.onNewSet}>New set <Plus size={15} /></button>}</div>{p.sets.length ? <div className="set-grid">{p.sets.slice(0, 4).map((set) => <SetCard key={set.id} set={set} onClick={() => p.onOpenSet(set.id)} onDuplicate={p.onDuplicateSet} onTrash={p.onTrashSet} />)}</div> : <div className="quiet-empty compact"><BookOpen size={20} /><p>Your flashcard sets will live here.</p></div>}</section></> }

function NewSetMenu({ aiEnabled, onCreate, onImport, onCreateAi }: { aiEnabled: boolean; onCreate: () => void; onImport: () => void; onCreateAi: () => void }) { const [open, setOpen] = useState(false); return <div className="new-set-menu"><button className="button button-primary button-small" onClick={() => setOpen((value) => !value)}><Plus size={15} /> New set</button>{open && <div className="paper-action-menu"><button onClick={() => { setOpen(false); onCreate() }}>Create</button><button onClick={() => { setOpen(false); onImport() }}>Import</button>{aiEnabled && <button className="ai-menu-action" onClick={() => { setOpen(false); onCreateAi() }}>Create with AI</button>}</div>}</div> }
function SetsLanding({ sets, allCards, aiEnabled, onNewSet, onImportSet, onNewAiSet, onOpenSet, onDuplicateSet, onTrashSet }: Pick<ClassViewProps, 'sets' | 'allCards' | 'aiEnabled' | 'onNewSet' | 'onImportSet' | 'onNewAiSet' | 'onOpenSet' | 'onDuplicateSet' | 'onTrashSet'>) { const [showAll, setShowAll] = useState(false); const menu = <NewSetMenu aiEnabled={aiEnabled} onCreate={onNewSet} onImport={onImportSet} onCreateAi={onNewAiSet} />; return <section><div className="section-heading"><div><h2>{showAll ? 'All cards' : 'Flashcard sets'}</h2><p>{showAll ? 'Every card in this class, collected in one place.' : 'Build sets quickly, then choose how you want to study.'}</p></div><div className="section-actions"><div className="view-toggle"><button className={!showAll ? 'active' : ''} onClick={() => setShowAll(false)}>Sets</button><button className={showAll ? 'active' : ''} onClick={() => setShowAll(true)}>All cards</button></div>{sets.length > 0 && menu}</div></div>{showAll ? <AllCards cards={allCards} onOpenSet={onOpenSet} /> : sets.length ? <div className="set-grid">{sets.map((set) => <SetCard key={set.id} set={set} onClick={() => onOpenSet(set.id)} onDuplicate={onDuplicateSet} onTrash={onTrashSet} />)}</div> : <div className="section-blank"><BookOpen size={26} /><h2>Nothing to review yet.</h2><p>Create a set when you’re ready to turn your papers into study material.</p>{menu}</div>}</section> }
function AllCards({ cards, onOpenSet }: { cards: Flashcard[]; onOpenSet: (setId: string) => void }) { if (!cards.length) return <div className="section-blank"><BookOpen size={26} /><h2>No cards in this class yet.</h2><p>Cards from every set will appear here automatically.</p></div>; return <div className="all-cards-list">{cards.map((card) => <button key={card.id} className="all-card-row" onClick={() => onOpenSet(card.setId)}><span><strong>{card.front}</strong><small>{card.back}</small></span>{card.isStarred && <Star size={14} fill="currentColor" />}</button>)}</div> }
function StudyLanding({ courseId, sets, onOpenSet, onStudyWeak }: Pick<ClassViewProps, 'sets' | 'onOpenSet' | 'onStudyWeak'> & { courseId: string }) { const [insights, setInsights] = useState<StudyInsights | null>(null); useEffect(() => { let active = true; void api.getStudyInsights(courseId).then((value) => { if (active) setInsights(value) }).catch(() => { if (active) setInsights(null) }); return () => { active = false } }, [courseId]); if (!sets.length) return <section className="section-blank"><Sparkles size={26} /><h2>Choose a set to study.</h2><p>Create a flashcard set first, then SoFlo will track what needs review.</p></section>; const firstWeak = insights?.weakCards[0]; const weakInSet = firstWeak ? insights?.weakCards.filter((card) => card.setId === firstWeak.setId).map((card) => card.cardId) ?? [] : []; return <section className="study-insights"><div className="section-heading"><div><p className="eyebrow">STUDY READINESS</p><h2>Pick up where your memory needs it.</h2><p>Results from Flashcards, Learn, Test, and Match all feed one shared review record.</p></div>{firstWeak ? <button className="button button-primary" onClick={() => onStudyWeak(firstWeak.setId, weakInSet)}><Sparkles size={15} /> Study weak areas</button> : <button className="button button-primary" onClick={() => onOpenSet(sets[0].id)}>Study {sets[0].title}</button>}</div>{insights ? <><div className="study-insight-counts"><span><strong>{insights.dueCards}</strong> ready for review</span><span><strong>{insights.needsWorkCards}</strong> need work</span><span><strong>{insights.masteredCards}</strong> mastered</span><span><strong>{insights.newCards}</strong> not studied yet</span></div><div className="study-insight-columns"><article><p className="eyebrow">FOCUS HERE</p>{insights.weakCards.length ? insights.weakCards.slice(0, 4).map((card) => <button key={card.cardId} onClick={() => onStudyWeak(card.setId, insights.weakCards.filter((item) => item.setId === card.setId).map((item) => item.cardId))}><strong>{card.term}</strong><span>{card.incorrectCount > card.correctCount ? `${card.incorrectCount} misses` : card.mastery === 'new' ? 'Not studied yet' : card.mastery === 'needsWork' ? 'Needs more review' : 'Keep practicing'}</span></button>) : <p className="insight-empty">Study a few cards and this will identify what needs attention.</p>}</article><article><p className="eyebrow">CRUSHING IT</p>{insights.strongCards.length ? insights.strongCards.map((card) => <button key={card.cardId} onClick={() => onOpenSet(card.setId)}><strong>{card.term}</strong><span>{card.correctCount} correct responses</span></button>) : <p className="insight-empty">Mastered concepts will appear here.</p>}</article></div></> : <div className="quiet-empty compact"><p>Loading your study record…</p></div>}</section> }
function TrashLanding({ documents, sets, onRestoreDocument, onRestoreSet }: { documents: DocumentSummary[]; sets: FlashcardSetSummary[]; onRestoreDocument: (id: string) => void; onRestoreSet: (id: string) => void }) { if (!documents.length && !sets.length) return <section className="section-blank"><Trash2 size={26} /><h2>Recently deleted</h2><p>Deleted papers and sets will stay here so one accidental click never destroys your work.</p></section>; return <section className="trash-list"><div className="section-heading"><div><h2>Recently deleted</h2><p>Restore anything you moved here by accident.</p></div></div>{documents.map((document) => <article className="trash-row" key={document.id}><FilePlus2 size={17} /><div><strong>{document.title || 'Untitled paper'}</strong><small>Paper · deleted {formatDate(document.deletedAt ?? document.updatedAt)}</small></div><button className="button button-soft button-small" onClick={() => onRestoreDocument(document.id)}><RotateCcw size={14} /> Restore</button></article>)}{sets.map((set) => <article className="trash-row" key={set.id}><BookOpen size={17} /><div><strong>{set.title}</strong><small>Flashcard set · deleted {formatDate(set.deletedAt ?? set.updatedAt)}</small></div><button className="button button-soft button-small" onClick={() => onRestoreSet(set.id)}><RotateCcw size={14} /> Restore</button></article>)}</section> }
function SetCard({ set, onClick, onDuplicate, onTrash }: { set: FlashcardSetSummary; onClick: () => void; onDuplicate: (set: FlashcardSetSummary, title: string) => void; onTrash: (set: FlashcardSetSummary) => void }) { const [menuOpen, setMenuOpen] = useState(false); const [duplicate, setDuplicate] = useState(false); const [title, setTitle] = useState(`${set.title} copy`); return <article className={`set-card${menuOpen ? ' menu-open' : ''}`}><button className="set-card-main" onClick={onClick}><span className="set-card-icon"><BookOpen size={19} /></span><span><strong>{set.title}</strong><small>{set.cardCount} {set.cardCount === 1 ? 'card' : 'cards'} · {formatDate(set.updatedAt)}</small></span></button><div className="paper-row-actions"><button className="icon-button tiny" aria-label={`Set settings for ${set.title}`} onClick={() => setMenuOpen((current) => !current)}><MoreHorizontal size={17} /></button>{menuOpen && <div className="paper-action-menu"><button onClick={() => { setMenuOpen(false); setDuplicate(true) }}><Copy size={14} /> Duplicate</button><button className="danger" onClick={() => { setMenuOpen(false); onTrash(set) }}><Trash2 size={14} /> Move to trash</button></div>}</div>{duplicate && <div className="paper-dialog-backdrop"><section className="paper-dialog" role="dialog" aria-modal="true"><header><h2>Duplicate flashcard set</h2><button className="icon-button" onClick={() => setDuplicate(false)}><X size={17} /></button></header><form onSubmit={(event) => { event.preventDefault(); if (title.trim()) { onDuplicate(set, title.trim()); setDuplicate(false) } }}><div className="paper-dialog-content"><label>New set name<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></label></div><footer><button type="button" className="button button-quiet" onClick={() => setDuplicate(false)}>Cancel</button><button className="button button-primary" disabled={!title.trim()}>Duplicate</button></footer></form></section></div>}</article> }
