import { Archive, BookOpen, CalendarDays, Copy, Download, FilePlus2, FileText, FileUp, GraduationCap, LayoutList, MoreHorizontal, NotebookPen, Plus, RotateCcw, Search, Sparkles, Star, Trash2, X } from 'lucide-react'
import { useEffect, useLayoutEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import type { AppView, CourseClass, DocumentDetail, DocumentFolder, DocumentSummary, Flashcard, FlashcardSetSummary, LectureSummary, StudyWebSummary } from '../../lib/types'
import { formatDate } from '../../lib/format'
import { api } from '../../lib/api'
import { DocumentsView } from '../editor/DocumentsView'
import { LecturesView } from '../lectures/LecturesView'
import { CourseCalendarView } from '../courseCalendar/CourseCalendarView'

interface ClassViewProps { course: CourseClass; tab: Extract<AppView, { kind: 'class' }>['tab']; documentCount: number; documents: DocumentSummary[]; folders: DocumentFolder[]; lectures: LectureSummary[]; syllabus: DocumentDetail | null; aiEnabled: boolean; trashedDocuments: DocumentSummary[]; sets: FlashcardSetSummary[]; trashedSets: FlashcardSetSummary[]; allCards: Flashcard[]; studyWebs: StudyWebSummary[]; onTab: (tab: Extract<AppView, { kind: 'class' }>['tab']) => void; onNewDocument: () => void; onNewLecture: () => void; onImportPdf: () => void; onImportSyllabus: () => void; onImportSyllabusWithAi: () => void; onEnsureAiModel: () => Promise<string | null>; onNewSet: () => void; onImportSet: () => void; onNewAiSet: () => void; onOpenDocument: (document: DocumentSummary) => void; onOpenLecture: (lecture: LectureSummary) => void; onDeleteLecture: (lecture: LectureSummary) => void; onTrashDocument: (document: DocumentSummary) => void; onDuplicateDocument: (document: DocumentSummary, title: string) => void; onBulkRename: (papers: { id: string; title: string }[]) => void; onGroupDocuments: (id: string, targetId: string) => void; onUngroupDocument: (id: string) => void; onRenameDocumentFolder: (id: string, title: string) => void; onOpenSet: (id: string) => void; onStudy: (setIds: string[], mode: 'flashcards' | 'learn' | 'test' | 'match' | 'teachItBack', cardIds?: string[]) => void; onStudyWeak: (setId: string, cardIds: string[]) => void; onCreateStudyWeb: (sets: FlashcardSetSummary[], existingWebId?: string) => void; onCreateEmptyStudyWeb: () => void; onImportStudyWeb: () => void; onOpenStudyWeb: (webId: string) => void; onDuplicateSet: (set: FlashcardSetSummary, title: string) => void; onTrashSet: (set: FlashcardSetSummary) => void; onRestoreDocument: (id: string) => void; onRestoreSet: (id: string) => void; onArchive: () => void; onToast: (message: string, kind?: 'success' | 'error') => void }
const tabs: { key: ClassViewProps['tab']; label: string; icon: typeof LayoutList }[] = [{ key: 'overview', label: 'Overview', icon: LayoutList }, { key: 'notes', label: 'Papers', icon: FilePlus2 }, { key: 'lectures', label: 'Lectures', icon: NotebookPen }, { key: 'syllabus', label: 'Syllabus', icon: FileText }, { key: 'courseCalendar', label: 'Course Calendar', icon: CalendarDays }, { key: 'flashcards', label: 'Flashcards', icon: BookOpen }, { key: 'studyWeb', label: 'Study Web', icon: Sparkles }, { key: 'trash', label: 'Trash', icon: Trash2 }]

export function ClassView(p: ClassViewProps) { return <main className="class-view"><header className="class-header content-view"><div className="class-title-line"><span className="large-class-icon" style={{ background: p.course.accentColor }}><GraduationCap size={21} /></span><div><p className="eyebrow">{p.course.courseCode || 'CLASS'}</p><h1>{p.course.name}</h1></div><button className="icon-button class-more" aria-label="Archive class" onClick={p.onArchive}><Archive size={17} /></button></div><div className="class-meta">{p.course.professor && <span>{p.course.professor}</span>}{p.course.location && <span>{p.course.location}</span>}{p.course.schedule && <span>{p.course.schedule}</span>}</div><nav className="class-tabs" aria-label={`${p.course.name} navigation`}>{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.key} className={p.tab === tab.key ? 'active' : ''} onClick={() => p.onTab(tab.key)}><Icon size={15} />{tab.label}</button> })}</nav></header><div className="content-view class-content">{p.tab === 'overview' && <Overview {...p} />}{p.tab === 'notes' && <DocumentsView documents={p.documents} folders={p.folders} aiEnabled={p.aiEnabled} onOpen={p.onOpenDocument} onCreate={p.onNewDocument} onImportPdf={p.onImportPdf} onTrash={p.onTrashDocument} onDuplicate={p.onDuplicateDocument} onBulkRename={p.onBulkRename} onGroup={p.onGroupDocuments} onUngroup={p.onUngroupDocument} onRenameFolder={p.onRenameDocumentFolder} />}{p.tab === 'lectures' && <LecturesView lectures={p.lectures} onCreate={p.onNewLecture} onOpen={p.onOpenLecture} onDelete={p.onDeleteLecture} />}{p.tab === 'syllabus' && <SyllabusView syllabus={p.syllabus} aiEnabled={p.aiEnabled} onImport={p.onImportSyllabus} onImportWithAi={p.onImportSyllabusWithAi} />}{p.tab === 'courseCalendar' && <CourseCalendarView course={p.course} aiEnabled={p.aiEnabled} onEnsureAiModel={p.onEnsureAiModel} onToast={p.onToast} />}{p.tab === 'flashcards' && <FlashcardsHub {...p} />}{p.tab === 'studyWeb' && <StudyWebLanding webs={p.studyWebs} sets={p.sets} aiEnabled={p.aiEnabled} onOpen={p.onOpenStudyWeb} onCreate={p.onCreateEmptyStudyWeb} onImport={p.onImportStudyWeb} onGenerate={p.onCreateStudyWeb} onToast={p.onToast} />}{p.tab === 'trash' && <TrashLanding classId={p.course.id} documents={p.trashedDocuments} sets={p.trashedSets} onRestoreDocument={p.onRestoreDocument} onRestoreSet={p.onRestoreSet} />}</div></main> }

function SyllabusImportButton({ aiEnabled, compact, onImport, onImportWithAi }: { aiEnabled: boolean; compact?: boolean; onImport: () => void; onImportWithAi: () => void }) { const [open, setOpen] = useState(false); const className = `button ${compact ? 'button-quiet button-small' : 'button-primary'}`; if (!aiEnabled) return <button className={className} onClick={onImport}><FileUp size={compact ? 15 : 16} /> {compact ? 'Replace syllabus' : 'Import syllabus'}</button>; return <div className="new-set-menu syllabus-import-menu"><button className={className} onClick={() => setOpen((value) => !value)}><FileUp size={compact ? 15 : 16} /> {compact ? 'Replace syllabus' : 'Import syllabus'}</button>{open && <div className="paper-action-menu"><button onClick={() => { setOpen(false); onImport() }}>Import document</button><button className="ai-menu-action" onClick={() => { setOpen(false); onImportWithAi() }}>Import with AI</button></div>}</div> }
function SyllabusView({ syllabus, aiEnabled, onImport, onImportWithAi }: { syllabus: DocumentDetail | null; aiEnabled: boolean; onImport: () => void; onImportWithAi: () => void }) { if (!syllabus) return <section className="section-blank syllabus-empty"><FileText size={28} /><h2>Add your class syllabus.</h2><p>Import a PDF, Word document, or downloadable Google Doc. SoFlo preserves the available structure in a read-only paper for this class.</p><SyllabusImportButton aiEnabled={aiEnabled} onImport={onImport} onImportWithAi={onImportWithAi} /></section>; return <section className="syllabus-view"><div className="section-heading"><div><h2>Syllabus</h2><p>Class syllabus.</p></div><SyllabusImportButton aiEnabled={aiEnabled} compact onImport={onImport} onImportWithAi={onImportWithAi} /></div><SyllabusContent syllabus={syllabus} /></section> }
type SyllabusNode = { type?: string; text?: string; marks?: { type?: string; attrs?: { href?: string } }[]; attrs?: { level?: number }; content?: SyllabusNode[] }
const nodeText = (node: SyllabusNode): string => node.text ?? node.content?.map(nodeText).join('') ?? ''
const syllabusText = (node: SyllabusNode): ReactNode => { if (node.type === 'hardBreak') return <br />; if (node.text === undefined) return node.content?.map((child, index) => <span key={index}>{syllabusText(child)}</span>); const text = node.marks?.some((mark) => mark.type === 'bold') ? <strong>{node.text}</strong> : markdownBold(node.text); const emphasized = node.marks?.some((mark) => mark.type === 'italic') ? <em>{text}</em> : text; const href = node.marks?.find((mark) => mark.type === 'link')?.attrs?.href; return href ? <a href={href} target="_blank" rel="noreferrer">{emphasized}</a> : emphasized }
const markdownBold = (text: string) => text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean).map((part, index) => part.startsWith('**') && part.endsWith('**') ? <strong key={index}>{part.slice(2, -2)}</strong> : <span key={index}>{part}</span>)
function SyllabusContent({ syllabus }: { syllabus: DocumentDetail }) {
  const nodes = useMemo(() => {
    try {
      const parsed = JSON.parse(syllabus.content) as SyllabusNode
      return parsed.content?.length ? parsed.content : [{ type: 'paragraph', content: [] }]
    } catch {
      return [{ type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: syllabus.title || 'Syllabus' }] }, { type: 'paragraph', content: [{ type: 'text', text: syllabus.contentPlain || 'This syllabus is empty.' }] }]
    }
  }, [syllabus.content, syllabus.contentPlain, syllabus.title])
  const measureRef = useRef<HTMLDivElement>(null)
  const [pageIndexes, setPageIndexes] = useState<number[][]>(() => [nodes.map((_, index) => index)])
  useLayoutEffect(() => {
    const measure = measureRef.current
    if (!measure) return
    let frame = 0
    const paginate = () => {
      const capacity = measure.clientHeight
      const elements = Array.from(measure.children) as HTMLElement[]
      if (!capacity || elements.length !== nodes.length) return
      const next: number[][] = [[]]
      let used = 0
      elements.forEach((element, index) => {
        const style = window.getComputedStyle(element)
        const height = element.getBoundingClientRect().height + Number.parseFloat(style.marginBottom || '0')
        if (next[next.length - 1].length && used + height > capacity) { next.push([]); used = 0 }
        next[next.length - 1].push(index)
        used += height
      })
      setPageIndexes((current) => JSON.stringify(current) === JSON.stringify(next) ? current : next)
    }
    const schedule = () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(paginate) }
    schedule()
    const observer = new ResizeObserver(schedule)
    observer.observe(measure)
    window.addEventListener('resize', schedule)
    return () => { cancelAnimationFrame(frame); observer.disconnect(); window.removeEventListener('resize', schedule) }
  }, [nodes])
  const pages = pageIndexes.flat().length === nodes.length ? pageIndexes : [nodes.map((_, index) => index)]
  return <><div className="syllabus-measure" ref={measureRef} aria-hidden="true">{nodes.map((node, index) => <div className="syllabus-node" key={index}>{renderNode(node, index)}</div>)}</div><div className="syllabus-page-stack">{pages.map((page, pageIndex) => <article className="document-page syllabus-paper" key={pageIndex}><div className="syllabus-paper-content">{page.map((nodeIndex) => <div className="syllabus-node" key={nodeIndex}>{renderNode(nodes[nodeIndex], nodeIndex)}</div>)}</div><span className="syllabus-page-number" aria-label={`Page ${pageIndex + 1}`}>{pageIndex + 1}</span></article>)}</div></>
}
function renderNode(node: SyllabusNode, key: number): ReactNode { const text = syllabusText(node); if (node.type === 'heading') { const Tag = `h${Math.min(6, Math.max(1, node.attrs?.level ?? 2))}` as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'; return <Tag key={key}>{text}</Tag> }; if (node.type === 'bulletList' || node.type === 'orderedList') { const Tag = node.type === 'bulletList' ? 'ul' : 'ol'; return <Tag key={key}>{node.content?.map((item, index) => <li key={index}>{syllabusText(item)}</li>)}</Tag> }; if (node.type === 'table') return <table key={key}><tbody>{node.content?.map((row, rowIndex) => <tr key={rowIndex}>{row.content?.map((cell, cellIndex) => cell.type === 'tableHeader' ? <th key={cellIndex}>{syllabusText(cell)}</th> : <td key={cellIndex}>{syllabusText(cell)}</td>)}</tr>)}</tbody></table>; if (node.type === 'horizontalRule') return <hr key={key} />; return <p key={key}>{text}</p> }

function Overview(p: ClassViewProps) { return <><section className="overview-hero" style={{ '--course-accent': p.course.accentColor } as React.CSSProperties}><div><p className="eyebrow">YOUR WORKSPACE</p><h2>Ready when you are.</h2><p>Write a paper, review a set, or pick up where you left off.</p></div><div className="overview-actions"><button className="button button-light" onClick={p.onNewDocument}><FilePlus2 size={16} /> New paper</button><button className="button button-soft" onClick={p.onNewSet}><BookOpen size={16} /> New set</button></div></section><section className="overview-metrics"><div><span>{p.documentCount}</span><small>{p.documentCount === 1 ? 'paper' : 'papers'}</small></div><div><span>{p.sets.length}</span><small>{p.sets.length === 1 ? 'flashcard set' : 'flashcard sets'}</small></div><div><span>{p.sets.reduce((total, set) => total + set.cardCount, 0)}</span><small>cards to review</small></div></section><section className="class-section"><div className="section-heading"><div><h2>Flashcard sets</h2><p>Keep your review material close to your papers.</p></div>{p.sets.length > 0 && <button className="text-button" onClick={p.onNewSet}>New set <Plus size={15} /></button>}</div>{p.sets.length ? <div className="set-grid">{p.sets.slice(0, 4).map((set) => <SetCard key={set.id} set={set} onClick={() => p.onOpenSet(set.id)} onDuplicate={p.onDuplicateSet} onTrash={p.onTrashSet} onToast={p.onToast} />)}</div> : <div className="quiet-empty compact"><BookOpen size={20} /><p>Your flashcard sets will live here.</p></div>}</section></> }

function NewSetMenu({ aiEnabled, onCreate, onImport, onCreateAi }: { aiEnabled: boolean; onCreate: () => void; onImport: () => void; onCreateAi: () => void }) { const [open, setOpen] = useState(false); return <div className="new-set-menu"><button className="button button-primary button-small" onClick={() => setOpen((value) => !value)}><Plus size={15} /> New set</button>{open && <div className="paper-action-menu"><button onClick={() => { setOpen(false); onCreate() }}>Create</button><button onClick={() => { setOpen(false); onImport() }}>Import</button>{aiEnabled && <button className="ai-menu-action" onClick={() => { setOpen(false); onCreateAi() }}>Create with AI</button>}</div>}</div> }
function FlashcardsHub(p: ClassViewProps) { const [section, setSection] = useState<'sets' | 'cards' | 'study'>('sets'); return <section className="flashcards-hub"><div className="flashcards-hub-tabs" role="tablist"><button className={section === 'sets' ? 'active' : ''} onClick={() => setSection('sets')}>Sets</button><button className={section === 'cards' ? 'active' : ''} onClick={() => setSection('cards')}>All cards</button><button className={section === 'study' ? 'active' : ''} onClick={() => setSection('study')}>Study</button></div>{section === 'sets' && <SetsLanding sets={p.sets} aiEnabled={p.aiEnabled} onNewSet={p.onNewSet} onImportSet={p.onImportSet} onNewAiSet={p.onNewAiSet} onOpenSet={p.onOpenSet} onDuplicateSet={p.onDuplicateSet} onTrashSet={p.onTrashSet} onToast={p.onToast} />}{section === 'cards' && <AllCards cards={p.allCards} onOpenSet={p.onOpenSet} />}{section === 'study' && <MultiSetStudyLanding sets={p.sets} aiEnabled={p.aiEnabled} onStudy={p.onStudy} />}</section> }
function MultiSetStudyLanding({ sets, aiEnabled, onStudy }: { sets: FlashcardSetSummary[]; aiEnabled: boolean; onStudy: ClassViewProps['onStudy'] }) { const [selected, setSelected] = useState<string[]>(() => sets.slice(0, 1).map((set) => set.id)); const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); useEffect(() => setSelected((current) => current.filter((id) => sets.some((set) => set.id === id))), [sets]); if (!sets.length) return <div className="section-blank"><Sparkles size={26} /><h2>Choose a set to study.</h2><p>Create a flashcard set first, then SoFlo will track what needs review.</p></div>; return <section className="multi-set-study"><div className="section-heading"><div><p className="eyebrow">STUDY</p><h2>Study one set or mix a few together.</h2><p>Select the material you want in this session.</p></div><button className="text-button" onClick={() => setSelected(selected.length === sets.length ? [] : sets.map((set) => set.id))}>{selected.length === sets.length ? 'Clear all' : 'Select all'}</button></div><div className="multi-set-picker">{sets.map((set) => <label key={set.id} className={selected.includes(set.id) ? 'selected' : ''}><input type="checkbox" checked={selected.includes(set.id)} onChange={() => toggle(set.id)} /><span><strong>{set.title}</strong><small>{set.cardCount} {set.cardCount === 1 ? 'card' : 'cards'}</small></span></label>)}</div><div className="multi-set-actions"><span>{selected.length ? `${selected.length} set${selected.length === 1 ? '' : 's'} selected` : 'Select at least one set'}</span><div><button className="button button-soft button-small" disabled={!selected.length} onClick={() => onStudy(selected, 'flashcards')}>Flashcards</button><button className="button button-primary button-small" disabled={!selected.length} onClick={() => onStudy(selected, 'learn')}><Sparkles size={15} /> Learn</button><button className="button button-soft button-small" disabled={!selected.length} onClick={() => onStudy(selected, 'test')}>Test</button><button className="button button-soft button-small" disabled={!selected.length} onClick={() => onStudy(selected, 'match')}>Match</button>{aiEnabled && <button className="button button-soft button-small ai-action" disabled={!selected.length} onClick={() => onStudy(selected, 'teachItBack')}>Teach It Back</button>}</div></div></section> }
function StudyWebCreateMenu({ aiEnabled, sets, onCreate, onImport, onGenerate }: { aiEnabled: boolean; sets: FlashcardSetSummary[]; onCreate: () => void; onImport: () => void; onGenerate: (sets: FlashcardSetSummary[]) => void }) {
  const [open, setOpen] = useState(false)
  const [pickerOpen, setPickerOpen] = useState(false)
  return <div className="new-set-menu study-web-create-menu">
    <button className="button button-primary button-small" aria-expanded={open} onClick={() => setOpen((value) => !value)}><Plus size={15} /> Create</button>
    {open && <div className="paper-action-menu"><button onClick={() => { setOpen(false); onCreate() }}>Create</button><button onClick={() => { setOpen(false); onImport() }}>Import</button>{aiEnabled && <button className="ai-menu-action" disabled={!sets.length} onClick={() => { setOpen(false); setPickerOpen(true) }}>Import with AI</button>}</div>}
    {pickerOpen && <StudyWebPicker sets={sets} onClose={() => setPickerOpen(false)} onCreate={(selected) => { setPickerOpen(false); onGenerate(selected) }} />}
  </div>
}

function StudyWebLanding({ webs, sets, aiEnabled, onOpen, onCreate, onImport, onGenerate, onToast }: { webs: StudyWebSummary[]; sets: FlashcardSetSummary[]; aiEnabled: boolean; onOpen: (id: string) => void; onCreate: () => void; onImport: () => void; onGenerate: (selectedSets: FlashcardSetSummary[]) => void; onToast: ClassViewProps['onToast'] }) {
  const [menuId, setMenuId] = useState<string | null>(null)
  const [hidden, setHidden] = useState<string[]>([])
  const visibleWebs = webs.filter((web) => !hidden.includes(web.id))
  const trash = async (web: StudyWebSummary) => {
    try {
      await api.setStudyWebDeleted(web.id, true)
      setHidden((current) => [...current, web.id])
      window.dispatchEvent(new CustomEvent('soflo:study-web-trash-changed'))
    } finally { setMenuId(null) }
  }
  const exportWeb = async (web: StudyWebSummary) => {
    setMenuId(null)
    try {
      await api.exportStudyWebJson(web.id)
      onToast('Study Web exported to Downloads.')
    } catch (error) {
      onToast(error instanceof Error ? error.message : 'Study Web could not be exported.', 'error')
    }
  }
  const menu = <StudyWebCreateMenu aiEnabled={aiEnabled} sets={sets} onCreate={onCreate} onImport={onImport} onGenerate={onGenerate} />
  return <section className="study-web-library"><div className="section-heading"><div><h2>Study Web</h2><p>Build a fresh study web or import it from a flashcard set with AI.</p></div>{visibleWebs.length > 0 && menu}</div>{visibleWebs.length ? <div className="study-web-grid">{visibleWebs.map((web) => <article className="study-web-card" key={web.id}><button className="study-web-card-main" onClick={() => onOpen(web.id)}><span className="set-card-icon"><Sparkles size={18} /></span><span><strong>{web.name}</strong><small>{web.cardCount} concepts · {web.groupCount} groups</small>{web.outOfDate && <em>Study Web out of date</em>}</span></button><div className="paper-row-actions"><button className="icon-button tiny" aria-label={`Study Web options for ${web.name}`} onClick={() => setMenuId((current) => current === web.id ? null : web.id)}><MoreHorizontal size={17} /></button>{menuId === web.id && <div className="paper-action-menu"><button onClick={() => void exportWeb(web)}><Download size={14} /> Export</button><button className="danger" onClick={() => void trash(web)}><Trash2 size={14} /> Move to trash</button></div>}</div></article>)}</div> : <div className="section-blank"><Sparkles size={26} /><h2>Build your first Study Web.</h2><p>Create one from scratch, bring in an exported web, or use flashcards with AI.</p><div className="study-web-first-action">{menu}</div></div>}</section>
}
function StudyWebPicker({ sets, onClose, onCreate }: { sets: FlashcardSetSummary[]; onClose: () => void; onCreate: (sets: FlashcardSetSummary[]) => void }) { const [query, setQuery] = useState(''); const [selected, setSelected] = useState<string[]>([]); const normalized = query.trim().toLocaleLowerCase(); const matches = normalized ? sets.filter((set) => set.title.toLocaleLowerCase().includes(normalized)) : sets; const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length >= 5 ? current : [...current, id]); return <div className="paper-dialog-backdrop"><section className="paper-dialog study-web-picker" role="dialog" aria-modal="true" aria-label="Choose flashcard sets"><header><div><p className="eyebrow">AI STUDY WEB</p><h2>Choose flashcard sets</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={17} /></button></header><div className="paper-dialog-content"><p>Select up to five sets. SoFlo will create one connected Study Web from their cards.</p><label className="study-web-picker-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search flashcard sets" autoFocus />{query && <button onClick={() => setQuery('')} aria-label="Clear search"><X size={14} /></button>}</label><div className="study-web-picker-list">{matches.map((set) => <button key={set.id} className={selected.includes(set.id) ? 'selected' : ''} onClick={() => toggle(set.id)}><span className="study-web-picker-check">{selected.includes(set.id) ? '✓' : ''}</span><span><strong>{set.title}</strong><small>{set.cardCount} {set.cardCount === 1 ? 'card' : 'cards'}</small></span></button>)}{!matches.length && <p>No flashcard sets match your search.</p>}</div><small className="study-web-picker-count">{selected.length} of 5 sets selected</small></div><footer><button className="button button-quiet" onClick={onClose}>Cancel</button><button className="button button-primary ai-action" disabled={!selected.length} onClick={() => onCreate(sets.filter((set) => selected.includes(set.id)))}><Sparkles size={15} /> Create Study Web</button></footer></section></div> }
function SetsLanding({ sets, aiEnabled, onNewSet, onImportSet, onNewAiSet, onOpenSet, onDuplicateSet, onTrashSet, onToast }: Pick<ClassViewProps, 'sets' | 'aiEnabled' | 'onNewSet' | 'onImportSet' | 'onNewAiSet' | 'onOpenSet' | 'onDuplicateSet' | 'onTrashSet' | 'onToast'>) { const menu = <NewSetMenu aiEnabled={aiEnabled} onCreate={onNewSet} onImport={onImportSet} onCreateAi={onNewAiSet} />; return <section><div className="section-heading"><div><h2>Flashcard sets</h2><p>Build sets quickly, then choose how you want to study.</p></div><div className="section-actions">{sets.length > 0 && menu}</div></div>{sets.length ? <div className="set-grid">{sets.map((set) => <SetCard key={set.id} set={set} onClick={() => onOpenSet(set.id)} onDuplicate={onDuplicateSet} onTrash={onTrashSet} onToast={onToast} />)}</div> : <div className="section-blank"><BookOpen size={26} /><h2>Nothing to review yet.</h2><p>Create a set when you’re ready to turn your papers into study material.</p>{menu}</div>}</section> }
function AllCards({ cards, onOpenSet }: { cards: Flashcard[]; onOpenSet: (setId: string) => void }) { const [query, setQuery] = useState(''); const normalized = query.trim().toLocaleLowerCase(); const results = normalized ? cards.filter((card) => `${card.front} ${card.back}`.toLocaleLowerCase().includes(normalized)) : cards; if (!cards.length) return <div className="section-blank"><BookOpen size={26} /><h2>No cards in this class yet.</h2><p>Cards from every set will appear here automatically.</p></div>; return <section className="all-cards-section"><div className="section-heading"><div><h2>All cards</h2><p>Every card in this class, collected in one place.</p></div><label className="all-cards-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search all cards" aria-label="Search all cards" />{query && <button onClick={() => setQuery('')} aria-label="Clear card search"><X size={14} /></button>}</label></div>{results.length ? <div className="all-cards-list">{results.map((card) => <button key={card.id} className="all-card-row" onClick={() => onOpenSet(card.setId)}><span><strong>{card.front}</strong><small>{card.back}</small></span>{card.isStarred && <Star size={14} fill="currentColor" />}</button>)}</div> : <div className="quiet-empty compact"><p>No cards match “{query.trim()}”.</p></div>}</section> }
function TrashLanding({ classId, documents, sets, onRestoreDocument, onRestoreSet }: { classId: string; documents: DocumentSummary[]; sets: FlashcardSetSummary[]; onRestoreDocument: (id: string) => void; onRestoreSet: (id: string) => void }) { const [webs, setWebs] = useState<StudyWebSummary[]>([]); useEffect(() => { void api.listTrashedStudyWebs(classId).then(setWebs).catch(() => setWebs([])) }, [classId]); const restoreWeb = async (id: string) => { await api.setStudyWebDeleted(id, false); setWebs((current) => current.filter((web) => web.id !== id)) }; if (!documents.length && !sets.length && !webs.length) return <section className="section-blank"><Trash2 size={26} /><h2>Recently deleted</h2><p>Deleted papers, Study Webs, and sets will stay here so one accidental click never destroys your work.</p></section>; return <section className="trash-list"><div className="section-heading"><div><h2>Recently deleted</h2><p>Restore anything you moved here by accident.</p></div></div>{documents.map((document) => <article className="trash-row" key={document.id}><FilePlus2 size={17} /><div><strong>{document.title || 'Untitled paper'}</strong><small>Paper · deleted {formatDate(document.deletedAt ?? document.updatedAt)}</small></div><button className="button button-soft button-small" onClick={() => onRestoreDocument(document.id)}><RotateCcw size={14} /> Restore</button></article>)}{sets.map((set) => <article className="trash-row" key={set.id}><BookOpen size={17} /><div><strong>{set.title}</strong><small>Flashcard set · deleted {formatDate(set.deletedAt ?? set.updatedAt)}</small></div><button className="button button-soft button-small" onClick={() => onRestoreSet(set.id)}><RotateCcw size={14} /> Restore</button></article>)}{webs.map((web) => <article className="trash-row" key={web.id}><Sparkles size={17} /><div><strong>{web.name}</strong><small>Study Web · deleted {formatDate(web.deletedAt ?? web.updatedAt)}</small></div><button className="button button-soft button-small" onClick={() => void restoreWeb(web.id)}><RotateCcw size={14} /> Restore</button></article>)}</section> }
function SetCard({ set, onClick, onDuplicate, onTrash, onToast }: { set: FlashcardSetSummary; onClick: () => void; onDuplicate: (set: FlashcardSetSummary, title: string) => void; onTrash: (set: FlashcardSetSummary) => void; onToast: ClassViewProps['onToast'] }) { const [menuOpen, setMenuOpen] = useState(false); const [duplicate, setDuplicate] = useState(false); const [title, setTitle] = useState(`${set.title} copy`); const exportSet = async () => { setMenuOpen(false); try { await api.exportFlashcardSetText(set.id); onToast('Flashcards exported to Downloads.') } catch (error) { onToast(error instanceof Error ? error.message : 'Flashcards could not be exported.', 'error') } }; return <article className={`set-card${menuOpen ? ' menu-open' : ''}`}><button className="set-card-main" onClick={onClick}><span className="set-card-icon"><BookOpen size={19} /></span><span><strong>{set.title}</strong><small>{set.cardCount} {set.cardCount === 1 ? 'card' : 'cards'} · {formatDate(set.updatedAt)}</small></span></button><div className="paper-row-actions"><button className="icon-button tiny" aria-label={`Set settings for ${set.title}`} onClick={() => setMenuOpen((current) => !current)}><MoreHorizontal size={17} /></button>{menuOpen && <div className="paper-action-menu"><button onClick={() => { setMenuOpen(false); setDuplicate(true) }}><Copy size={14} /> Duplicate</button><button onClick={() => void exportSet()}><Download size={14} /> Export</button><button className="danger" onClick={() => { setMenuOpen(false); onTrash(set) }}><Trash2 size={14} /> Move to trash</button></div>}</div>{duplicate && <div className="paper-dialog-backdrop"><section className="paper-dialog" role="dialog" aria-modal="true"><header><h2>Duplicate flashcard set</h2><button className="icon-button" onClick={() => setDuplicate(false)}><X size={17} /></button></header><form onSubmit={(event) => { event.preventDefault(); if (title.trim()) { onDuplicate(set, title.trim()); setDuplicate(false) } }}><div className="paper-dialog-content"><label>New set name<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></label></div><footer><button type="button" className="button button-quiet" onClick={() => setDuplicate(false)}>Cancel</button><button className="button button-primary" disabled={!title.trim()}>Duplicate</button></footer></form></section></div>}</article> }
