import { CalendarDays, Clock3, MapPin, UserRound } from 'lucide-react'
import type { CourseClass } from '../../lib/types'

const dayPatterns: Record<number, RegExp> = { 0: /\b(sun|sunday)\b/i, 1: /\b(mon|monday|m\/w\/f|m\s*[,&/]\s*w)\b/i, 2: /\b(tue|tues|tuesday|t\/th|t\s*[,&/]\s*th)\b/i, 3: /\b(wed|wednesday|m\/w\/f|m\s*[,&/]\s*w)\b/i, 4: /\b(thu|thur|thurs|thursday|t\/th|t\s*[,&/]\s*th)\b/i, 5: /\b(fri|friday|m\/w\/f)\b/i, 6: /\b(sat|saturday)\b/i }
const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
function timeValue(schedule: string) { const match = schedule.match(/(\d{1,2})(?::(\d{2}))?\s*(a\.?m\.?|p\.?m\.?)/i); if (!match) return Number.MAX_SAFE_INTEGER; let hour = Number(match[1]) % 12; if (match[3].toLowerCase().startsWith('p')) hour += 12; return hour * 60 + Number(match[2] ?? 0) }
function scheduleForDay(schedule: string, day: number) { const token = dayNames[day]; const exact = schedule.match(new RegExp(`${token}\\s+(\\d{1,2}(?::\\d{2})?\\s*(?:a\\.?m\\.?|p\\.?m\\.?))(?:\\s*-\\s*(\\d{1,2}(?::\\d{2})?\\s*(?:a\\.?m\\.?|p\\.?m\\.?)))?`, 'i')); return exact ? `${exact[1]}${exact[2] ? ` - ${exact[2]}` : ''}` : schedule.match(/\d{1,2}(?::\d{2})?\s*(?:a\.?m\.?|p\.?m\.?)/i)?.[0] ?? 'Time TBA' }

export function CalendarView({ classes }: { classes: CourseClass[] }) {
  const today = new Date(); const day = today.getDay(); const todayClasses = classes.filter((course) => course.schedule && dayPatterns[day].test(course.schedule)).sort((first, second) => timeValue(scheduleForDay(first.schedule ?? '', day)) - timeValue(scheduleForDay(second.schedule ?? '', day))); const dayLabel = new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(today)
  return <main className="calendar-view content-view"><header className="view-intro"><p className="eyebrow">CALENDAR</p><h1>Today</h1><p>{dayLabel}</p></header><section className="day-agenda"><header><span><CalendarDays size={18} /><strong>Your classes today</strong></span><small>{todayClasses.length ? `${todayClasses.length} on your schedule` : 'No classes scheduled'}</small></header>{todayClasses.length ? <div className="day-agenda-list">{todayClasses.map((course) => <article className="day-agenda-row" key={course.id} style={{ '--course-accent': course.accentColor } as React.CSSProperties}><span className="day-agenda-time"><Clock3 size={15} />{scheduleForDay(course.schedule ?? '', day)}</span><i /><div><strong>{course.courseCode || course.name}</strong><span>{course.name}</span><small>{course.professor && <><UserRound size={12} />{course.professor}</>}{course.location && <><MapPin size={12} />{course.location}</>}</small></div></article>)}</div> : <div className="calendar-empty"><CalendarDays size={28} /><h2>A clear day.</h2><p>Use Set class schedule when creating a class and it will appear here automatically.</p></div>}</section></main>
}
